[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "quadrs"
version = "0.1.0"

[dependencies]
byteorder = "1.1.0"
error-chain = "0.11.0"
regex = "0.2.2"
rustfft = "2.0.0"
[profile.release]
lto = true
