[package]
name = "octagon"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
anyhow = "1"
byteorder = "1"
num-complex = "0.3"
num-traits = "0.2"
regex = "1"
rustfft = "5"

