[package]
name = "octagon"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
byteorder = "1"
failure = "0.1"
num-complex = "0.1"
num-traits = "0.2"
regex = "0.2"
rustfft = "2"
