[package]
name = "octagon"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
byteorder = "1"
error-chain = "0.11"
num-complex = "0.1"
num-traits = "0.1"
regex = "0.2"
rustfft = "2"
