[package]
name = "tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
error-chain = "0.11"
image = "0.18"
palette = "0.2"
regex = "0.2"
rustfft = "2"

[dependencies.conrod]
# 0.57 is BUSTED on linux: https://github.com/PistonDevelopers/conrod/issues/1120
version = "~0.56"
features = ["glium", "winit"]

[dependencies.octagon]
path = "../octagon"
