[package]
name = "quadrs"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
error-chain = "0.11"
image = "0.18"
palette = "0.3"
regex = "0.2"
rustfft = "2"

[dependencies.conrod]
version = "0.58"
features = ["glium", "winit"]

[dependencies.octagon]
path = "../octagon"
