[package]
name = "quadrs"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
anyhow = "1"
image = "0.22"
palette = "0.4"
regex = "1"
rustfft = "5"
rusttype = "0.8"

[dependencies.conrod]
version = "0.61"
features = ["glium", "winit"]

[dependencies.octagon]
path = "../octagon"
