[package]
name = "quadrs"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
cast = "0.2"
failure = "0.1"
image = "0.18"
palette = "0.3"
regex = "0.2"
rustfft = "2"
rusttype = "*"

[dependencies.conrod]
version = "0.59"
features = ["glium", "winit"]

[dependencies.octagon]
path = "../octagon"
